language: cpp

os:
- linux
- osx

dist: trusty

python: '2.7'

install:
  - nvm install 8.9.4

before_script:
  - ./ensure_dependencies.py
  - npm install

script:
  - npm test

notifications:
  email: false
