"use strict";

const MIN_PASSWORD_LENGTH = 8;
const MAX_PASSWORD_LENGTH = 30;
const VALID_WALLET_ADDRESS_LENGTH = 25;

module.exports = {
  MIN_PASSWORD_LENGTH,
  MAX_PASSWORD_LENGTH,
  VALID_WALLET_ADDRESS_LENGTH
};
